# Generated by Django 3.2.6 on 2021-11-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.TextField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
            ],
            options={
                'db_table': "COURSE'.'category",
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.TextField()),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_url', models.URLField()),
                ('course_img', models.URLField(blank=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('min_price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('length', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='course_filter.category')),
            ],
            options={
                'db_table': "COURSE'.'course",
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.TextField(primary_key=True, serialize=False)),
                ('status_description', models.TextField()),
            ],
            options={
                'db_table': "COURSE'.'status",
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.TextField(primary_key=True, serialize=False)),
                ('teacher_name', models.TextField()),
                ('teacher_img', models.URLField()),
                ('teacher_introduction', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': "COURSE'.'teacher",
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('website_id', models.TextField(primary_key=True, serialize=False)),
                ('website_url', models.URLField()),
            ],
            options={
                'db_table': "COURSE'.'website",
            },
        ),
        migrations.CreateModel(
            name='StudentsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_of_course', to='course_filter.course')),
            ],
            options={
                'db_table': "COURSE'.'students_count",
            },
        ),
        migrations.CreateModel(
            name='Fundraising',
            fields=[
                ('fundraising_id', models.TextField(primary_key=True, serialize=False)),
                ('fundraising_due_date', models.DateField()),
                ('fundraising_process', models.FloatField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_on_course', to='course_filter.course')),
            ],
            options={
                'db_table': "COURSE'.'fundraising",
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.TextField(primary_key=True, serialize=False)),
                ('discount_content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_on_course', to='course_filter.course')),
            ],
            options={
                'db_table': "COURSE'.'discount",
            },
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='course_filter.status'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='course_filter.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='course_filter.website'),
        ),
    ]
