# Generated by Django 3.2.6 on 2021-11-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='COURSE"."category',
        ),
        migrations.AlterModelTable(
            name='course',
            table='COURSE"."course',
        ),
        migrations.AlterModelTable(
            name='discount',
            table='COURSE"."discount',
        ),
        migrations.AlterModelTable(
            name='fundraising',
            table='COURSE"."fundraising',
        ),
        migrations.AlterModelTable(
            name='status',
            table='COURSE"."status',
        ),
        migrations.AlterModelTable(
            name='studentscount',
            table='COURSE"."students_count',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='COURSE"."teacher',
        ),
        migrations.AlterModelTable(
            name='website',
            table='COURSE"."website',
        ),
    ]
