# Generated by Django 3.2.6 on 2021-11-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_filter', '0002_auto_20211103_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_img',
            new_name='course_img_url',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_description',
            new_name='course_intro',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='length',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
