# Generated by Django 3.2.6 on 2021-11-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_filter', '0003_auto_20211103_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
